### PR TITLE
Added temporary patch for WebSocket

### PR DESCRIPTION
**Pull request by e39a562r**
Here are some changes I made for myself to avoid issue #38.

It has a problem I've no idea how to workaround, so...

Please merge it **only when** it really saves your time. 🙏    

### Changes
- Skip inner loop of ConversationType.PROMPT when the response data is an url of websocket.
- Replace the value `blocked` flag from `true` to `false` for every websocket message.

### Problems
- Unable to fetch latest conversation for user when the message is blocked, due to unable to intercept websocket with asynchronous function.

### Cause of the issue #38
- ChatGPT responsing conversation with only an url of websocket

image

### CODE REVIEW

**Comment by 4as** [comment]
Thank you for handling this issue.  
For now I am yet to run into the same problem, so I can't yet verify whether this fix works or not. As soon as they roll out the changes to my region I'll take a look and do a review.  
In the mean time can you confirm that your changes also handle yellow and red warnings?
Also does the fix work on iOS (Safari with UserScripts) and Android (KiwiBrowser)?

**Comment by e39a562r** [comment]
Uh I just install Kiwi Browser (what a nice app)  on my android, and ...... it is **not affected** by issue #38 ! 😂  

Now I also have to wait. 🤣🤣🤣 

### Updates
- Snooze yellow warnings from websocket message.

### TODO
- Test this branch on iOS device,  (find an iOS device first)
- Wait until the bug happen on my android Kiwi Browser.

**Comment by e39a562r** [comment]
The problem is disappeared. 🚀

**Comment by ysy95109** [comment]
This solves the recent [issue 38](https://github.com/4as/ChatGPT-DeMod/issues/38).

**Comment by 4as** [comment]
In the latest update to DeMod I've added changes that I think resolve the issue related to this pull request, so I'm closing it, as it's probably no longer needed.

**Pull request closed without merging**
