### PR TITLE
Removed content warnings from moderated conversations

### PR DESCRIPTION
**Pull request by brink182**
This will remove the content warnings on flagged messages (e.g. from conversations with DeMod disabled). The removal is not persistent and content warnings will reappear if DeMod is off.

### CODE REVIEW

**Comment by 4as** [comment]
Sorry, I can't accept these changes. This is not what DeMod is about. You're removing the indication that a messaged has been flagged for moderation, which could be understand by the end user as the script "cleaning" the conversation from any wrong doing, while in fact it's a lie. OpenAI has flagged the conversation and there is no turning that around. The user should know that.
Currently DeMod actually makes a real change. There is no pretending, no presenting a different view of the reality, it actually stops the moderation check from being triggered. OpenAI doesn't get to know something was inappropriate. 
I want it to stay that way. It displays the real state of the conversation at all times.

**Comment by brink182** [comment]
That's a valid concern. The real problem with the content warnings I see is that the messages markup is not rendered correctly. Removing them was the easiest fix. Would you accept an pr that only fixes the markup while keeping the warning (orange box and note)?

**Comment by 4as** [comment]
I actually don't have any active content warnings to see what you're talking about, so I can't really say if it will be something I'm going to accept. Feel free to create a separate pull request with the changes you want to see and an explanation of what the problem is. Once I see, and it makes sense, I'm probably going to accept it.

**Comment by brink182** [comment]
I have no good solution yet, but here is a script demonstrating the problem. https://github.com/brink182/ChatGPT-DeMod/raw/feature/filter_conversation_moderation/ChatGPT%20DeMod%20-%20Markdown%20problem%20demo.user.js . It replaces all conversations with a flagged markdown demo. DeMod is included, make sure to disable other scripts and reload the conversation when you toggle DeMod.

**Pull request closed without merging**
